# Generated by Django 2.2.4 on 2019-09-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title of message')),
                ('description', models.TextField(verbose_name='description of message')),
                ('published_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='object name')),
                ('company', models.CharField(max_length=200, verbose_name='object company name')),
                ('category', models.CharField(max_length=200, verbose_name='object category')),
                ('specifications', models.CharField(max_length=1000, verbose_name='object specifications')),
                ('image', models.ImageField(max_length=200, upload_to='db/images/%Y/%m/%d/', verbose_name='object image')),
                ('sheet', models.FileField(blank=True, max_length=200, null=True, upload_to='db/sheet/%Y/%m/%d/', verbose_name='object sheet')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
