# Generated by Django 2.2.4 on 2019-09-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='object name')),
                ('company', models.CharField(max_length=200, verbose_name='object company name')),
                ('category', models.CharField(max_length=200, verbose_name='object category')),
                ('Specifications', models.CharField(max_length=1000, verbose_name='object Specifications')),
            ],
        ),
    ]
