# Generated by Django 2.2.4 on 2019-09-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20190913_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
