# Generated by Django 2.2.4 on 2019-09-15 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20190913_1304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
