# Generated by Django 2.2.4 on 2019-09-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_delete_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100, verbose_name='tag name')),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='tag',
            field=models.ManyToManyField(to='shop.Tag'),
        ),
    ]
